site_name: Projeto 1 Cloud - Docker & RESTful API
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Landing Page: index.md
  - Aplicação Local:
    - Home: local_index.md
    - Técnico: local_tech.md
  - Aplicação AWS:
    - Home: aws_index.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences
