name: cloud_project1

services:
  app:
    image: pedrodl/cloud_project1:latest
    container_name: fast_api_cloud
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRS_HOST:-db}:5432/${POSTGRES_DB:-ProjetoCloud}
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: postgres_db_cloud
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ProjetoCloud}
    # Expondo na porta 5430 para não conflitar com o postgres local
    ports:
      - "5430:5432"