name: cloud_project1

services:
  app:
    image: pedrodl/cloud_project1:latest
    container_name: fast_api_cloud
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ProjetoCloud
    depends_on:
      - db
    volumes:
      - .:/app
  
  db:
    image: postgres_cloud
    container_name: postgres_db_cloud
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ProjetoCloud}
    # Expondo na porta 5430 para não conflitar com o postgres local
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: